# syntax=docker/dockerfile:1.7

FROM node:20.19.4-alpine AS base
ENV PNPM_HOME="/pnpm"
ENV PATH="${PNPM_HOME}:${PATH}"
RUN corepack enable

FROM base AS build
WORKDIR /app
ENV HUSKY=0

COPY package.json pnpm-lock.yaml ./
RUN pnpm install --frozen-lockfile

COPY . .

ARG VITE_API_BASE_URL
ARG VITE_CURRENCY_LOCALE
ARG VITE_CURRENCY_CODE
ARG VITE_CURRENCY_PRECISION
ARG VITE_FIREBASE_API_KEY
ARG VITE_FIREBASE_AUTH_DOMAIN
ARG VITE_FIREBASE_PROJECT_ID
ARG VITE_FIREBASE_STORAGE_BUCKET
ARG VITE_FIREBASE_MESSAGING_SENDER_ID
ARG VITE_FIREBASE_APP_ID

ENV VITE_API_BASE_URL="${VITE_API_BASE_URL}"
ENV VITE_CURRENCY_LOCALE="${VITE_CURRENCY_LOCALE}"
ENV VITE_CURRENCY_CODE="${VITE_CURRENCY_CODE}"
ENV VITE_CURRENCY_PRECISION="${VITE_CURRENCY_PRECISION}"
ENV VITE_FIREBASE_API_KEY="${VITE_FIREBASE_API_KEY}"
ENV VITE_FIREBASE_AUTH_DOMAIN="${VITE_FIREBASE_AUTH_DOMAIN}"
ENV VITE_FIREBASE_PROJECT_ID="${VITE_FIREBASE_PROJECT_ID}"
ENV VITE_FIREBASE_STORAGE_BUCKET="${VITE_FIREBASE_STORAGE_BUCKET}"
ENV VITE_FIREBASE_MESSAGING_SENDER_ID="${VITE_FIREBASE_MESSAGING_SENDER_ID}"
ENV VITE_FIREBASE_APP_ID="${VITE_FIREBASE_APP_ID}"

RUN pnpm build

FROM nginxinc/nginx-unprivileged:1.27-alpine AS runtime
WORKDIR /usr/share/nginx/html

COPY docker/nginx/default.conf /etc/nginx/conf.d/default.conf
COPY --from=build /app/dist ./

EXPOSE 8080

HEALTHCHECK --interval=30s --timeout=5s --start-period=10s --retries=3 \
  CMD wget --no-verbose --tries=1 --spider http://127.0.0.1:8080/healthz || exit 1
