module.exports = {
  preset: 'ts-jest',
  testEnvironment: 'jsdom',
  roots: ['<rootDir>/src'],
  transform: {
    '^.+\\.(ts|tsx)$': 'ts-jest',
  },
  moduleNameMapper: {
    '^@app/(.*)$': '<rootDir>/src/app/$1',
    '^@core/http/client.instance$': '<rootDir>/src/__mocks__/client.instance.mock.ts',
    '^@core/utils/mask$': '<rootDir>/src/__mocks__/mask.mock.ts',
    '^@modules/work-order/services/work-order-api$': '<rootDir>/src/__mocks__/work-order-api.mock.ts',
    '^@core/(.*)$': '<rootDir>/src/core/$1',
    '^@shared/(.*)$': '<rootDir>/src/shared/$1',
    '^@modules/(.*)$': '<rootDir>/src/modules/$1',
  },
  setupFilesAfterEnv: ['<rootDir>/jest.setup.ts'],
  testMatch: ['**/?(*.)+(spec|test).ts', '**/?(*.)+(spec|test).tsx'],
  coveragePathIgnorePatterns: [
    '/node_modules/',
    '/presentation/',
    '/__mocks__/',
  ],
  collectCoverage: true,
  collectCoverageFrom: [
    'src/core/auth/**/*.ts',
    'src/modules/users/services/auth.service.ts',
    'src/modules/users/services/user.service.ts',
    'src/modules/users/services/users-api.ts',
    'src/modules/users/services/assistant-chat-api.ts',
    'src/modules/users/services/assistant-chat.service.ts',
    'src/modules/users/services/notifications-api.ts',
    'src/modules/users/services/notifications.service.ts',
    'src/modules/users/services/overview-api.ts',
    'src/modules/users/services/overview.service.ts',
    'src/modules/billing/services/billing-api.ts',
    'src/modules/billing/services/billing.service.ts',
    'src/modules/billing/services/invoice-settings-api.ts',
    'src/modules/billing/services/invoice-settings.service.ts',
    'src/modules/people/services/people-api.ts',
    'src/modules/people/services/people.service.ts',
    'src/modules/people/services/workforce-capacity.service.ts',
    'src/modules/inventory/services/inventory-api.ts',
    'src/modules/inventory/services/inventory.service.ts',
    'src/modules/inventory/services/inventory.http.service.ts',
    'src/modules/clients/services/clients-360-api.ts',
    'src/modules/growth/services/growth-api.ts',
    'src/modules/growth/services/growth.service.ts',
    'src/modules/schedule/services/schedule.service.ts',
    'src/modules/schedule/services/schedules-api.ts',
    'src/modules/work-order/services/work-order.http.service.ts',
    'src/modules/work-order/services/work-order-api.ts',
  ],
  coverageThreshold: {
    global: { branches: 70, functions: 70, lines: 70, statements: 70 },
    'src/modules/billing/services/': { branches: 70, functions: 70, lines: 70, statements: 70 },
    'src/modules/people/services/': { branches: 70, functions: 70, lines: 70, statements: 70 },
    'src/modules/inventory/services/': { branches: 70, functions: 70, lines: 70, statements: 70 },
    'src/modules/users/services/': { branches: 70, functions: 70, lines: 70, statements: 70 },
  },
  globals: {
    'ts-jest': {
      tsconfig: 'tsconfig.app.json',
      isolatedModules: true,
    },
  },
};
