import type { ServiceModel } from "@modules/clients/interfaces/service.model";

export async function getAvailableServices(): Promise<ServiceModel[]> {
  await new Promise((r) => setTimeout(r, 80));

  const items: ServiceModel[] = [
    {
      id: "svc-01",
      title: "Mendes Barber",
      description: "Cortes masculinos e barba profissional.",
      providerId: "prov-01",
      providerName: "Mendes Barber",
      address: "Rua Guttmann, 62 - Jardim Santo Eduardo, Embu das Artes",
      imageUrl: "https://picsum.photos/seed/mendes/640/420",
      rating: 5.0,
      reviewsCount: 189,
      featured: true,
      priceCents: 4500,
      priceFormatted: "R$ 45,00",
      tags: ["barbearia", "beleza"],
    },
    {
      id: "svc-02",
      title: "Barbearia JJ",
      description: "Equipe qualificada e ambiente moderno.",
      providerId: "prov-02",
      providerName: "Barbearia JJ",
      address: "Avenida Perimetral Sul, 606, Vila Rica",
      imageUrl: "https://picsum.photos/seed/jj/640/420",
      rating: 4.9,
      reviewsCount: 197,
      featured: false,
      priceCents: 6000,
      priceFormatted: "R$ 60,00",
      tags: ["barbearia"],
    },
    {
      id: "svc-03",
      title: "Barbearia Edynho",
      description: "Atendimento rápido e impecável.",
      providerId: "prov-03",
      providerName: "Barbearia Edynho",
      address: "Rua Lagoa da Tocha, 166, São Paulo",
      imageUrl: "https://picsum.photos/seed/edynho/640/420",
      rating: 5.0,
      reviewsCount: 477,
      featured: false,
      priceCents: 5500,
      priceFormatted: "R$ 55,00",
      tags: ["barbearia"],
    },
    {
      id: "svc-04",
      title: "The Black White Hair",
      description: "Instituto de beleza especializado.",
      providerId: "prov-04",
      providerName: "The Black White Hair",
      address: "Avenida Doutor Arnaldo, 251, Consolação",
      imageUrl: "https://picsum.photos/seed/blackhair/640/420",
      rating: 4.7,
      reviewsCount: 447,
      featured: false,
      priceCents: 8000,
      priceFormatted: "R$ 80,00",
      tags: ["beleza", "cabelo"],
    },
    {
      id: "svc-05",
      title: "QUOTI Studio",
      description: "Fotografia e estúdio criativo.",
      providerId: "prov-05",
      providerName: "QUOTI Studio",
      address: "Rua das Flores, 12, Centro",
      imageUrl: "https://picsum.photos/seed/quoti/640/420",
      rating: 4.6,
      reviewsCount: 102,
      featured: false,
      priceCents: 120000,
      priceFormatted: "R$ 1.200,00",
      tags: ["fotografia", "criativo"],
    },
    {
      id: "svc-06",
      title: "Studio Verde",
      description: "Design e desenvolvimento web.",
      providerId: "prov-06",
      providerName: "Studio Verde",
      address: "Av. Brasil, 900, Sala 5",
      imageUrl: "https://picsum.photos/seed/studioverde/640/420",
      rating: 4.8,
      reviewsCount: 64,
      featured: false,
      priceCents: 350000,
      priceFormatted: "R$ 3.500,00",
      tags: ["web", "design"],
    },
    {
      id: "svc-07",
      title: "Casa do Sabor",
      description: "Buffet e gastronomia para eventos.",
      providerId: "prov-07",
      providerName: "Casa do Sabor",
      address: "Praça Central, 1",
      imageUrl: "https://picsum.photos/seed/casadosabor/640/420",
      rating: 4.5,
      reviewsCount: 210,
      featured: false,
      priceCents: 150000,
      priceFormatted: "R$ 1.500,00",
      tags: ["culinaria", "evento"],
    },
    {
      id: "svc-08",
      title: "Auto Mecânica Pro",
      description: "Revisões e consertos automotivos.",
      providerId: "prov-08",
      providerName: "Auto Mecânica Pro",
      address: "Av. Oficina, 45",
      imageUrl: "https://picsum.photos/seed/automec/640/420",
      rating: 4.4,
      reviewsCount: 88,
      featured: false,
      priceCents: 250000,
      priceFormatted: "R$ 2.500,00",
      tags: ["auto", "servico"],
    },
    {
      id: "svc-09",
      title: "Flor & Arte",
      description: "Decoração e arranjos florais.",
      providerId: "prov-09",
      providerName: "Flor & Arte",
      address: "Rua Primavera, 77",
      imageUrl: "https://picsum.photos/seed/florarte/640/420",
      rating: 4.3,
      reviewsCount: 34,
      featured: false,
      priceCents: 9000,
      priceFormatted: "R$ 90,00",
      tags: ["decoração", "flores"],
    },
    {
      id: "svc-10",
      title: "Academia Viva",
      description: "Personal trainer e aulas coletivas.",
      providerId: "prov-10",
      providerName: "Academia Viva",
      address: "Rua do Esporte, 200",
      imageUrl: "https://picsum.photos/seed/academia/640/420",
      rating: 4.2,
      reviewsCount: 145,
      featured: false,
      priceCents: 120000,
      priceFormatted: "R$ 1.200,00",
      tags: ["saude", "fitness"],
    },
  ];

  return items;
}

export default { getAvailableServices };
