steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - -f
      - Dockerfile
      - --build-arg
      - VITE_API_BASE_URL=${_VITE_API_BASE_URL}
      - --build-arg
      - VITE_CURRENCY_LOCALE=${_VITE_CURRENCY_LOCALE}
      - --build-arg
      - VITE_CURRENCY_CODE=${_VITE_CURRENCY_CODE}
      - --build-arg
      - VITE_CURRENCY_PRECISION=${_VITE_CURRENCY_PRECISION}
      - --build-arg
      - VITE_FIREBASE_API_KEY=${_VITE_FIREBASE_API_KEY}
      - --build-arg
      - VITE_FIREBASE_AUTH_DOMAIN=${_VITE_FIREBASE_AUTH_DOMAIN}
      - --build-arg
      - VITE_FIREBASE_PROJECT_ID=${_VITE_FIREBASE_PROJECT_ID}
      - --build-arg
      - VITE_FIREBASE_STORAGE_BUCKET=${_VITE_FIREBASE_STORAGE_BUCKET}
      - --build-arg
      - VITE_FIREBASE_MESSAGING_SENDER_ID=${_VITE_FIREBASE_MESSAGING_SENDER_ID}
      - --build-arg
      - VITE_FIREBASE_APP_ID=${_VITE_FIREBASE_APP_ID}
      - -t
      - ${_IMAGE_URI}
      - .

images:
  - ${_IMAGE_URI}

options:
  logging: CLOUD_LOGGING_ONLY

substitutions:
  _IMAGE_URI: us-docker.pkg.dev/example/example/worklyhub-frontend:latest
  _VITE_API_BASE_URL: https://api.example.com/api/v1
  _VITE_CURRENCY_LOCALE: en-US
  _VITE_CURRENCY_CODE: USD
  _VITE_CURRENCY_PRECISION: "2"
  _VITE_FIREBASE_API_KEY: ""
  _VITE_FIREBASE_AUTH_DOMAIN: worklyhub-9735f.firebaseapp.com
  _VITE_FIREBASE_PROJECT_ID: worklyhub-9735f
  _VITE_FIREBASE_STORAGE_BUCKET: worklyhub-9735f.firebasestorage.app
  _VITE_FIREBASE_MESSAGING_SENDER_ID: "421430807448"
  _VITE_FIREBASE_APP_ID: "1:421430807448:web:ccb6d1f098ca558d61f9ed"
